# Generated by Django 3.1.3 on 2020-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_suscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='age',
            field=models.IntegerField(),
        ),
    ]
